apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: us.gcr.io/local-bliss-456810-k7/inventory-api:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-srv
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
    - name: inventory
      protocol: TCP
      port: 3000
      targetPort: 5000
