name: Build & Push Docker Image to GCR

on:
  push:
    branches:
      - main # Run on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ secrets.GCR_REGION }} -q

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.GCR_REGION }}/${{ secrets.GCP_PROJECT_ID }}/inventory-api:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Output Docker Image URL
        run: |
          IMAGE="${{ secrets.GCR_REGION }}/${{ secrets.GCP_PROJECT_ID }}/inventory-api:latest"
          echo "Docker image pushed: $IMAGE"
        shell: bash

      - name: Set up kubectl
        uses: google-github-actions/setup-kubectl@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          zone: ${{ secrets.GKE_CLUSTER_ZONE }}
      - name: Set kubeconfig
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f inventory.yaml
